language: python
python:
  - 3.6
  - 3.7
install:
  - pip install --upgrade pip
  - pip install --no-cache-dir -U -r requirements.txt | cat
script:
  - pytest -v --cov=matrix --cov-report term-missing
after_success:
  - coveralls